---
name: Node.js app
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
